doctrine_migrations:

  storage:
    table_storage:
      table_name: doctrine_migration_versions

  migrations_paths:
      'DoctrineMigrations': '%kernel.project_dir%/migrations'

  all_or_nothing: true
  check_database_platform: true
