language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - APP_ENV=test
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=disabled

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - composer install
  - ./bin/phpunit install
  - 

script:
  - ./bin/phpunit
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console lint:xliff translations
  - ./bin/console security:check
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
