language: generic
dist: bionic
os: linux

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - ~/.symfony

env:
  global:
    - APP_ENV=test
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=disabled

before_install:
  - nvm install 12.18.1
  - nvm use 12.18.1
  - phpenv shell 7.4.2
  - composer self-update
  - |
    if [ ! -f ~/.symfony/bin/symfony ]; then
      wget https://get.symfony.com/cli/installer -O - | bash
    fi

install:
  - composer install
  - npm ci
  - ./bin/phpunit install
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:migrations:migrate -n
  - ./bin/console doctrine:fixtures:load -n
  - npm run-script build

script:
  - ./bin/phpunit
  - sed -i 's/var\/cache\/dev/var\/cache\/test/gI' phpstan.neon
  - sed -i 's/App_KernelDevDebugContainer/App_KernelTestDebugContainer/gI' phpstan.neon
  - ./vendor/bin/phpstan analyse --memory-limit 2G
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console lint:xliff translations
  - ~/.symfony/bin/symfony security:check
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
