#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_index:
    path: /admin
    controller: App\Controller\Admin\IssueController::index

app_logout:
    path: /logout

legacy_article_redirect:
    path: /article/{slug}/{id}
    controller: App\Controller\ArchiveController::legacyArticle

legacy_issue_redirect:
    path: /issue/{issueDate}
    controller: App\Controller\ArchiveController::legacyIssue
